gui:
  returnImmediately: true
logs:
  timestamps: false
  since: '' # set to '' to show all logs
  tail: '1000' # set to 200 to show last 200 lines of logs
customCommands:
  containers:
    - name: dumpLogs
      shell: true 
      command: 'docker logs {{ .Container.ID }} > /tmp/lzd-{{ .Container.Name }} && echo -n "cat /tmp/lzd-{{ .Container.Name }}" | XDG_SESSION_TYPE=x11 xsel -ib'
      serviceNames: []
